### ISSUE TITLE
汉化建议

### ISSUE THREAD

**Issue by maxupeng** [SunnyEric/NetHack_android#1]
感谢SunnyEric大大！！！
目前的汉化方式是直接修改源码，这样不利于合并主仓库的后续修改。
我有个不修改源码的方案如下：
1. 我可以写个工具把所有C字符串提取出来（基于ANTLR4）。提取内容包含字符串本身，以及字符串在源文件中的行数/开始索引/结束索引。
2. 翻译提取的字符串，也许到贴吧请大家一起翻译是个好主意 :)
3. 原文件 + 翻译后的字符串 -> 新文件
4. 编译新文件

SunnyEric大大觉得怎样？

**Comment by SunnyYuer** [comment]
感谢你提这个建议，你说的第3步 原文件 + 翻译后的字符串 -> 新文件，这个是怎么相加而得新文件的

**Comment by maxupeng** [comment]
因为第一步提取的内容包含了字符串以及字符串在源文件中的坐标，所以做下字符串的替换就可以得到翻译后的新文件了

**Comment by SunnyYuer** [comment]
这还是改了源码了嘛，最后替换掉源代码里的字符串了，不过这样也行。
你这样就是把源代码文件，变成了全字符串文档文件，同样都是改字符串嘛。
我在百度贴吧发帖就是请人来帮忙汉化的，可是却没多少人。变成全字符串文档文件后，也不见得有多少人。
我剩余还没有修改的，你可以用你的方法来，到时候合并也是一样的，不会有问题的。

**Comment by maxupeng** [comment]
这样做的最大好处是只要维护好字符串映射就行。
每次官方修改了源文件字符串，我们只需要重新提取，然后对比出发生变动的部分重新翻译即可。
不用每次都手动去改源文件。

PS：我英语渣 --!

**Comment by maxupeng** [comment]
提取工具见：https://github.com/maxupeng/nethack_string_extractor/releases/tag/v0.1

**Comment by SunnyYuer** [comment]
明白你的意思了，每当nethack出新版本时，这样确实易于维护。
这种方法真的可实施吗，你看看下面的代码
if (wizard && (!strncmpi(bp, "bear", 4) || !strncmpi(bp, "land", 4))) {
if (wizard && (!strncmpi(bp, "捕兽", sl=6) || !strncmpi(bp, "地", sl=3))) {
if (!strncmpi(zp, beartrap ? "trap" : "mine", 4)) {
if (!strncmpi(zp, beartrap ? "夹" : "雷", 3)) {
bear trap翻译为 捕兽夹，land mine翻译为 地雷
但在strncmpi()函数的最后一个参数要和字符大小一致，utf8下"bear"为4，"捕兽" 为6，必须要修改才行。

另外一种情况
原来的代码
pline_The("list price of %s%s%s is %ld %s%s.",
                      (contentscount && !obj->unpaid) ? the_contents_of : "",
                      the(xname(obj)),
                      (contentscount && obj->unpaid) ? and_its_contents : "",
                      ltmp, currency(ltmp), (obj->quan > 1L) ? " each" : "");
翻译后的
pline_The("%s%s的标价%s 是%s %ld %s.",
                      the(xname(obj)),
                      (contentscount && !obj->unpaid) ? the_contents_of : "",
                      (contentscount && obj->unpaid) ? and_its_contents : "",
                      (obj->quan > 1L) ? "每个" : "",
                      ltmp, currency(ltmp));
翻译后其中参数顺寻都换了个位置，否则语句不通。

还有就是，官方修改源代码之后，有些行数都发生了变化，这样字符串映射几乎全要修改行数。不知道你打算怎么办。

**Comment by maxupeng** [comment]
恩，我考虑的确实不够周全

```
if (wizard && (!strncmpi(bp, "bear", 4) || !strncmpi(bp, "land", 4))) {
if (wizard && (!strncmpi(bp, "捕兽", sl=6) || !strncmpi(bp, "地", sl=3))) {
if (!strncmpi(zp, beartrap ? "trap" : "mine", 4)) {
if (!strncmpi(zp, beartrap ? "夹" : "雷", 3)) {
```

这种情况可以根据strncmpi的函数调用来提取。

```
pline_The("list price of %s%s%s is %ld %s%s.",
(contentscount && !obj->unpaid) ? the_contents_of : "",
the(xname(obj)),
(contentscount && obj->unpaid) ? and_its_contents : "",
ltmp, currency(ltmp), (obj->quan > 1L) ? " each" : "");
```

这种情况我们可以人工提取？

```
官方修改源代码之后，有些行数都发生了变化
```

这个好办，只要字符串没变，我们重新提取后，可以从原来的映射表拿到对应的翻译

**Comment by SunnyYuer** [comment]
总之，你看着办吧(⊙v⊙)，你说的那种方法也不简单。

**Comment by maxupeng** [comment]
```
pline_The("list price of %s%s%s is %ld %s%s.",
(contentscount && !obj->unpaid) ? the_contents_of : "",
the(xname(obj)),
(contentscount && obj->unpaid) ? and_its_contents : "",
ltmp, currency(ltmp), (obj->quan > 1L) ? " each" : "");
```

不用人工，把所有pline_The函数调用的入参列表都提取出来就好。

**Comment by maxupeng** [comment]
哈哈，确实，有点想太多了。
而且，根本问题是没人翻译啊。。。

**Comment by SunnyYuer** [comment]
其实挺好的，如果真的做出来了，就可以翻译为多国语言了。

**Comment by maxupeng** [comment]
今天仔细看了源码，还是直接改源码比较方便。。。

**Comment by SunnyYuer** [comment]
嗯我目前还是直接改源码吧。
今天运行了下你的程序，感觉好厉害~

**Comment by G2159687** [comment]
我也可以尝试翻译一下，不过我对C语言一窍不通。可以像贴吧的931451545一样，给我一个文本文件，我可以翻译一些东西。
