### ISSUE TITLE
一些翻译改进

### ISSUE THREAD

**Issue by htfy96** [SunnyEric/NetHack_android#11]
1. 
```
src/dig.c
1335:            You_feel("到一个突然的草案.");
1347:            You_feel("到一个草案.");
```
You feel a sudden draft，应该是感受到一股突然的气流

2. dented pot 目前译作“瘪罐”，但作为帽子在tiles里长这样：
![dented pot](https://nethackwiki.com/mediawiki/images/4/48/Dented_pot.png)
“瘪锅”应该比较合适

3. Snickersnee的翻译
目前的版本中翻译成了“草薙剑”。但这个词在出处的The Mikado中是行刑官 Ko-Ko 处决犯人用的短刀，因此不太可能指神器之一。Snickersnee是snicker + snee （刺 + 切）的一个合成词，整部剧是在戏谑的氛围中发明这个自造词的，直译就是”能刺能切的东西“。现代有时候以它的用途指”行刑刀”（带幽默性质），也泛指任何能够用来打斗的东西（幽默）：
>  As late as 1976, according to the October 18 issue of Newsweek, Howard W. Smith, a Virginia Democrat, defended his use of the House Rules Committee chairmanship to block civil-rights legislation by quipping, "[Y]ou grasp any snickersnee you can get hold of and fight the best way you can."

> KO. 
The criminal cried, as he dropped him down, 
In a state of wild alarm  
With a frightful, frantic, fearful frown, 
I bared my big right arm. 
I seized him by his little pig-tail, 
And on his knees fell he, 
   As he squirmed and struggled, 
   And gurgled and guggled, 
I drew my snickersnee! 
            Oh,   never   shall   I   
            Forget   the   cry,   
Or the shriek that shrieked he, 
   As I gnashed my teeth, 
   When from its sheath 
I drew my snickersnee! 

这个的翻译还需要讨论一下，但“草薙剑”翻译应该是不太妥当的

4. loadstone 本来是lodestone （磁石）的意思，原版的梗是字面可以解释成负重(load) 石。翻译成中文“磁石”后失去了load这个梗，和游戏内容没什么联系。相比之下丢弃原梗翻译成“负重石”可能会更好一些。

5. demilich：半巫妖 -> 半神巫妖？是lich的进化版，后者是老翻译

**Comment by SunnyYuer** [comment]
抱歉过年没上GitHub。
1，2，4已改
3 我暂时没有什么好的翻译
5 半神巫妖翻译不恰当，游戏通关后就是成为半神，这个demilich就成了半神了？还是 半巫妖 比较好

**Comment by htfy96** [comment]
5的话看了一下目前的翻译，四种lich按照difficulty分别翻译成了“巫妖”、“半巫妖”、“巫妖大师”和“大巫妖”。

支持翻译成”半神巫妖“的理由：
- demilich的demi[主要体现在不再需要lich的body](https://rpg.stackexchange.com/questions/59928/since-when-were-demiliches-weaker-than-regular-liches)，更接近于lesser而不是half的含义，翻译成“半”容易引起是不完全的”巫妖“、比”巫妖“更弱的联想。

不支持的理由：
- 和”神“没有关系

两种翻译目前都有人一直在使用，也有妥协的翻译成了”半神级巫妖“

**Comment by SunnyYuer** [comment]
相比于‘’半神巫妖‘’有着“半神”的联想，“半巫妖”更弱的联想的问题小得多。
dnd中较普遍的翻译还是半巫妖。可以参考[半巫妖](https://baike.baidu.com/item/%E5%8D%8A%E5%B7%AB%E5%A6%96/2135582?fr=aladdin)
