### ISSUE TITLE
能否提供双语切换功能

### ISSUE THREAD

**Issue by physercoe** [SunnyEric/NetHack_android#12]
有些内容用中文搜不到教程和相关知识，得搜原版英文，在nethack wiki上找，但是不知道中文对应的英文是什么，希望可以增加语言切换功能，切换回英文原版。

**Comment by SunnyYuer** [comment]
切换这个功能不可能的，但我提供了有物品和怪物的英汉对照。
https://pan.baidu.com/s/1kVEXwSR
