### ISSUE TITLE
请在readme.md中写入完成比

### ISSUE THREAD

**Issue by Coioidea** [SunnyEric/NetHack_android#4]
请在readme.md中写入完成比
，另外，可以pull吗

**Comment by SunnyYuer** [comment]
目前还有以下的文件内容没有汉化（2016-9-4记录）
dbridge.c
dog.c
makemon.c
minion.c
mklev.c
mkobj.c
muse.c 多
music.c 多
pray.c 多
priest.c
region.c
steed.c
wield.c

**Comment by Coioidea** [comment]
dat/tribute文件是什么？需要汉化吗？

**Comment by SunnyYuer** [comment]
这个是小说魔法书的内容吧，我自己不打算汉化的，你想汉化的话也行。
另外有些东西我提醒下你
像下面这些函数
debugpline0()
panic()
等等，都不是显示在游戏里的，就不用汉化了。
注意下语句的通顺，有些函数不是你汉化的，可能不知道上下文的意思。实在没法通顺的话，就先那样吧。
看了下你提交的，我晚上回去合并再看下。

**Comment by SunnyYuer** [comment]
这些文件已经全部汉化完了，nethack也基本上汉化完成~(≧▽≦)/~啦啦啦，还是感谢你啦，问下你是否愿意出现在贡献者名单上https://github.com/SunnyEric/NetHack-Android/blob/master/nethack-android-ch/sys/android/res/values/credits.xml

**Comment by Coioidea** [comment]
哦，那谢谢啦

**Comment by Coioidea** [comment]
When shall we start the NetHack translation?
I replied you on the Baidu Tieba.
Will you start the translation?

**Comment by SunnyYuer** [comment]
原本我想等NetHack安卓汉化版稳定下来不会出bug后再去弄NetHack汉化，不过现在似乎是时候了。这个月内我会开个头的。
